services:
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stat-tackle
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
